repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 1.1.0
    hooks:
      - id: sync_with_poetry
        args: []

  - repo: local
    hooks:
      - id: black
        name: Check Black
        entry: poetry run black 
        pass_filenames: false
        language: system
        types: [python]
      - id: ruff
        name: Check Ruff
        entry: poetry run ruff
        #pass_filenames: false
        language: system
        types: [python]
