repos:
  - repo: local
    hooks:
      - id: black
        name: Check Black
        entry: poetry run black .
        pass_filenames: false
        language: system
        stages: [commit-msg]

      - id: ruff
        name: Check Ruff
        entry: poetry run ruff .
        pass_filenames: false
        language: system
        stages: [commit-msg]

      - id: interrogate
        name: Check Interrogate
        entry: poetry run interrogate .
        pass_filenames: false
        language: system
        stages: [commit-msg]

      - id: bandit
        name: Check Bandit
        entry: poetry run bandit -c pyproject.toml .
        pass_filenames: false
        language: system
        stages: [commit-msg]

      - id: pytest
        name: Check PyTest (Unit Tests)
        entry: poetry run pytest tests/
        pass_filenames: false
        language: system
        stages: [commit-msg]

      - id: commitizen
        name: Check Commitizen
        entry: cz check --allow-abort --commit-msg-file .git/COMMIT_EDITMSG
        pass_filenames: false
        language: system
        stages: [commit-msg]
