version: '3.5'
services:
  api-server:
    container_name: api-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USERNAME=
      - PASSWORD=
      - IMAPPATH=
      - LOGLEVEL=debug
    ports:
      - 8000:80
